# Generated by Django 4.0.6 on 2024-04-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_event_case_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='case_id',
        ),
    ]
