# Generated by Django 4.0.6 on 2024-04-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_event_address1_evt_event_address2_evt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alien_number_evt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='amount_paid_evt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='biometrics_filed_evt',
            field=models.BooleanField(default=False, verbose_name='Biometrics filed?'),
        ),
        migrations.AddField(
            model_name='event',
            name='e_28_filed_evt',
            field=models.BooleanField(default=False, verbose_name='E28 filed ?'),
        ),
        migrations.AddField(
            model_name='event',
            name='erop_evt',
            field=models.BooleanField(default=False, verbose_name='Erop ?'),
        ),
        migrations.AddField(
            model_name='event',
            name='foia_submitted_evt',
            field=models.BooleanField(default=False, verbose_name='Foia submitted?'),
        ),
        migrations.AddField(
            model_name='event',
            name='foia_uploaded_evt',
            field=models.BooleanField(default=False, verbose_name='Foia uploaded?'),
        ),
        migrations.AddField(
            model_name='event',
            name='hearing_date_evt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Hearing Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='hearing_location_evt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='i_589_filed_evt',
            field=models.BooleanField(default=False, verbose_name='I 59 filed ?'),
        ),
        migrations.AddField(
            model_name='event',
            name='total_billing_amount_evt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='work_permit_applied_evt',
            field=models.BooleanField(default=False, verbose_name='Work permit applied?'),
        ),
    ]
