# Generated by Django 4.0.6 on 2024-04-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrecord',
            name='alien_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='courttype',
            name='biometrics_filed',
            field=models.BooleanField(default=False, verbose_name='Biometrics filed?'),
        ),
        migrations.AddField(
            model_name='courttype',
            name='e_28_filed',
            field=models.BooleanField(default=False, verbose_name='E28 filed ?'),
        ),
        migrations.AddField(
            model_name='courttype',
            name='erop',
            field=models.BooleanField(default=False, verbose_name='Erop ?'),
        ),
        migrations.AddField(
            model_name='courttype',
            name='foia_submitted',
            field=models.BooleanField(default=False, verbose_name='Foia submitted?'),
        ),
        migrations.AddField(
            model_name='courttype',
            name='foia_uploaded',
            field=models.BooleanField(default=False, verbose_name='Foia uploaded?'),
        ),
        migrations.AddField(
            model_name='courttype',
            name='hearing_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Hearing Date'),
        ),
        migrations.AddField(
            model_name='courttype',
            name='hearing_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='courttype',
            name='i_589_filed',
            field=models.BooleanField(default=False, verbose_name='I 59 filed ?'),
        ),
        migrations.AddField(
            model_name='courttype',
            name='work_permit_applied',
            field=models.BooleanField(default=False, verbose_name='Work permit applied?'),
        ),
    ]
